# Generated by Django 3.1.5 on 2021-01-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'ordering': ['-date_posted']},
        ),
    ]
